# Generated by Django 5.1.6 on 2025-02-24 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkinout',
            name='check_in_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='checkinout',
            name='check_out_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
